version: 0.2

phases:
  install: 
    commands:
      - echo Installing Node 12...
      - npm i npm@latest -g
     
  pre_build:
    commands:
      - echo Installing dependencies...............
      - npm install
  build:
    commands:
      - npm run build
      - echo Testing...
      - echo Building...
      - yarn build
     
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
